### ISSUE TITLE
onResume api is not working.

### ISSUE THREAD

**Issue by rahulsinghvuclip** [micnews/react-jw-player#83] opened 2018-02-06 08:58 UTC
Hi team,
I tried to use onResume api. But this api is not working.

**Comment by ellell** [comment] 2018-02-06 09:03
Hey @rahulsinghvuclip, how is it not working? Could you provide some sample code showing how you're trying to use it?

**Comment by rahulsinghvuclip** [comment] 2018-02-06 10:39
this is just sample code i have given.
onPlay, onVideoLoad is working but not onResume


import React from 'react';
import ReactJWPlayer from 'react-jw-player';


class VideoPlayer extends React.Component {
 
  onPlay = () => {
     console.log('play');
  };
  onVideoLoad() {
     console.log('firstload');
  }
  onResume() {
    console.log('resume');
  }
  render() {
   return (
      <div className={playerSizeClass}>
        <ReactJWPlayer
          {...this.props}
          playerId={this.playerId}
          playerScript="xxx"
          licenseKey="xxx"
          onAdPlay={this.onAdPlay}
          onReady={this.initPlayer}
          onVideoLoad={this.onVideoLoad}
          onPlay={this.onPlay}
          onResume={this.onResume}
        />
      </div>
    );
  }
}

export default VideoPlayer;

**Comment by ellell** [comment] 2018-02-07 11:58
@rahulsinghvuclip I'm not able to reproduce this, just tried something similar on my end and resume callback is calling correctly for me. Any more details you can provide around this? 
Note that `onResume` is not supposed to be called on the first play, but only when you paused the player and then press play again.

**Comment by rahulsinghvuclip** [comment] 2018-02-07 13:27
import React from 'react';
import ReactJWPlayer from 'react-jw-player';
import './VideoPlayer.css';


class VideoPlayer extends React.Component {
  constructor(props) {
    super(props);
    this.player = null;
    this.playerId = 'viu-video-player';
    this.myIndex = 1;
  }

  initPlayer = () => {
    this.player = window.jwplayer(this.playerId);
  	console.log(this.player)
  };
  setInitialQuality() {
    //  console.log(this.player.getQualityLevels());
  }

  videoEnd = () => {
    this.player.on('complete', () => {});
  };
  removePlayer = () => {
    this.player.on('remove', () => {});
  };

 



  onPlay = () => {};
  onVideoLoad() {
     console.log('sf');
  }
  onResume() {
    console.log('sfc');
  }
  render() {
    const { layoutMode } = this.props;

    let playerSizeClass = 'player-size--small';
    switch (layoutMode) {
      case LAYOUT_MODE.BASIC:
        break;
      case LAYOUT_MODE.SMALL:
        playerSizeClass = 'player-size--small';
        break;
      case LAYOUT_MODE.MEDIUM:
        playerSizeClass = 'player-size--medium';
        break;
      case LAYOUT_MODE.LARGE:
        playerSizeClass = 'player-size--large';
        break;
      default:
        break;
    }

    return (
      <div className={playerSizeClass}>
        <ReactJWPlayer
          {...this.props}
          playerId={this.playerId}
          playerScript="xxx"
          licenseKey="xxx"
          onAdPlay={this.onAdPlay}
          onReady={this.initPlayer}
          onVideoLoad={this.onVideoLoad}
          onPlay={this.onPlay}
          onResume={this.onResume}
        />
      </div>
    );
  }
}

export default VideoPlayer;

**Comment by ellell** [comment] 2018-02-07 13:57
Ah, thanks for that. This seems to be an issue with jw player version 8, it is working correctly for version 7. I don't have capacity to fixing this right now, but pull requests are always welcome!

**Comment by rahulsinghvuclip** [comment] 2018-02-07 14:39
Hi Team,
This feature is required for my project. @danmakenoise

**Comment by zentuit** [comment] 2018-02-22 21:18
Looks like the event sent to the onPlay function has `oldstate` of 'buffering' and not 'paused'.  This is causing problems for us too.

**Comment by danmakenoise** [comment] 2018-02-25 06:01
@zentuit looks like you are correct. When we created this, JW Player v6 must've had a `paused` state, which is now `buffering`.

Are you able to make a PR for this?

**Comment by ellell** [comment] 2018-08-31 08:06
Fixed by https://github.com/micnews/react-jw-player/pull/108

**Closed by ellell** 2018-08-31 08:06 UTC
